@Library("jenlib") _

try {

	boolean deploy = env.GERRIT_EVENT_TYPE == "change-merged"

	Map<String, Object> pipelineOptions = [
		projects           : ["documentation-brainscales2"],
		container          : [app: "dls"],
		moduleOptions      : [modules: ["ppu-toolchain"]],
		notificationChannel: "#jenkins-trashbin",  // success is checked globally
		ignoreGerritChanges: deploy
	]

	withCcache() {
		wafDefaultPipeline(pipelineOptions)
	}

	stage("Archive Results") {
		runOnSlave(label: "frontend") {
			// NFS flush, but filelist might come handy anyways
			jesh("find doc/ -exec ls -lisa {} \\; > filelist_doc.txt")

			archiveArtifacts("filelist_doc.txt, doc/sphinx_documentation_brainscales2/**/*")
			publishHTML([allowMissing: false,
			             keepAll     : true,
			             reportDir   : "doc/sphinx_documentation_brainscales2",
			             reportFiles : "index.html",
			             reportName  : "BrainScaleS-2 User Documentation"])
		}
	}

	conditionalStage(name: "Deployment to GitHub Pages", skip: !deploy) {
		runOnSlave(label: "frontend") {
			dir("build/") {
				lock("documentation-brainscales2_GITHUB-UPLOAD") {
					jesh("git clone -b gh-pages git@github.com:electronicvisions/documentation-brainscales2.git gh-pages")
					jesh("rm -rf gh-pages/latest")
					jesh("cp -a documentation-brainscales2/html/html/. gh-pages/latest")
					dir("gh-pages") {
						jesh("../../documentation-brainscales2/.ci/generate_index.sh")
						jesh("git add index.html")
						jesh("git add latest/")
						jesh("git commit -m \"build ${currentBuild.projectName} ${currentBuild.displayName}\"")
						jesh("git remote add github git@github-documentation-brainscales2_gh-pages:electronicvisions/documentation-brainscales2.git")
						jesh("git push github")
					}
				}
			}
		}
	}

} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#dls-software")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}
